
#ifndef BLIZZARD_DMX_DEFINES_H
#define BLIZZARD_DMX_DEFINES_H

#include <inttypes.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DMX_RED (CONFIG_DMX_ADDRESS)
#define DMX_GREEN (CONFIG_DMX_ADDRESS + 1)
#define DMX_BLUE (CONFIG_DMX_ADDRESS + 2)

#define DMX_BACKGROUND (CONFIG_DMX_ADDRESS + 3)
#define DMX_BACKGROUND_SPEED (CONFIG_DMX_ADDRESS + 4)
#define DMX_BACKGROUND_CONTROL (CONFIG_DMX_ADDRESS + 5)
#define DMX_BACKGROUND_ALT_CONTROL (CONFIG_DMX_ADDRESS + 6)

#define DMX_FOREGROUND (CONFIG_DMX_ADDRESS + 7)
#define DMX_FOREGROUND_SPEED (CONFIG_DMX_ADDRESS + 8)
#define DMX_FOREGROUND_CONTROL (CONFIG_DMX_ADDRESS + 9)

#define DMX_X_CONTROL (CONFIG_DMX_ADDRESS + 10)
#define DMX_Y_CONTROL (CONFIG_DMX_ADDRESS + 11)

#define BACKGROUND_SOLID 25
#define BACKGROUND_STROBE 50
#define BACKGROUND_COLS 75
#define BACKGROUND_ROWS 100
#define BACKGROUND_CROSS 125
#define BACKGROUND_PLAID 150
#define BACKGROUND_SPARKLES 175
#define BACKGROUND_RAINBOW_FADE 225
#define BACKGROUND_RAINBOW_STROBE 256

#define FOREGROUND_NONE 25
#define FOREGROUND_ARROWS 50
#define FOREGROUND_DANGER 75
#define FOREGROUND_CHECK 100
#define FOREGROUND_MOUNT 125
#define FOREGROUND_CAMO 150
#define FOREGROUND_SOC 175
#define FOREGROUND_BLIZZARD 200
#define FOREGROUND_RUN 225
#define FOREGROUND_PAC 235
#define FOREGROUND_RS 245
#define FOREGROUND_GAME 256 

#define MODE_FADE 0
#define MODE_FLASH 1

#ifdef __cplusplus
}
#endif

#endif