#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := Blizzard_Bridge

EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/components/Lighting_Manager/
EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/components/Storage_Manager/
EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/components/UI_Manager/


include $(IDF_PATH)/make/project.mk
include sdkconfig

export IDF_PATH
